#!/bin/bash

### Separate file for this part of the build process. The goal is to unify parts of the build process by making modules that are used across several builds
dnf5 -y install \
fastfetch \
cowsay \
yt-dlp \
xcb-util-cursor \
i2c-tools \
libnsl \
powertop \
steam-devices \
google-noto-fonts-all \
rsms-inter-fonts \
xhost \
firewall-config \
gnome-shell-extension-appindicator

# Media plugins
dnf5 -y install \
svt-av1 \
svt-vp9 \
gstreamer1-plugin-openh264 \
gstreamer1-vaapi \
gstreamer-plugins-espeak \
gstreamer1-plugins-ugly \
mesa-vdpau-drivers.x86_64 \
mesa-vdpau-drivers.i686

# Custom mutter with triple buffering patch
dnf5 -y swap --repo=copr:copr.fedorainfracloud.org:trixieua:mutter-patched mutter mutter

# Pop in Bazzite patched stuff
dnf5 -y swap --repo copr:copr.fedorainfracloud.org:bazzite-org:bazzite bootc bootc
#for toswap in pipewire bluez xorg-x11-server-Xwayland; do \
for toswap in pipewire bluez; do \
dnf5 -y swap --repo copr:copr.fedorainfracloud.org:bazzite-org:bazzite-multilib $toswap $toswap; \
done && unset -v toswap

# Installing FirefoxPWA to save headaches later (disabled because repo died)
# rpm --import https://packagecloud.io/filips/FirefoxPWA/gpgkey
# echo -e "[firefoxpwa]\nname=FirefoxPWA\nmetadata_expire=7d\nbaseurl=https://packagecloud.io/filips/FirefoxPWA/rpm_any/rpm_any/\$basearch\ngpgkey=https://packagecloud.io/filips/FirefoxPWA/gpgkey\nrepo_gpgcheck=1\ngpgcheck=0\nenabled=1" | tee /etc/yum.repos.d/firefoxpwa.repo
# dnf5 -y makecache -y --disablerepo="*" --enablerepo="firefoxpwa"
# dnf5 -y install firefoxpwa
