#!/bin/bash

### Separate file for this part of the build process. The goal is to unify parts of the build process by making modules that are used across several builds
dnf5 -y install \
fastfetch \
yt-dlp \
cowsay \
xcb-util-cursor \
i2c-tools \
libnsl \
powertop \
steam-devices \
google-noto-fonts-all \
rsms-inter-fonts \
xhost \
firewall-config \
glfw \
glfw-devel \
stb-devel \
openssl-libs

# Media plugins
dnf5 -y install \
LCEVCdec \
svt-av1 \
svt-vp9 \
gstreamer1-plugin-openh264 \
gstreamer1-vaapi \
gstreamer-plugins-espeak \
gstreamer1-plugin-libav \
gstreamer1-plugin-vaapi \
gstreamer1-plugins-bad \
gstreamer1-plugins-ugly \
mesa-vdpau-drivers.x86_64 \
mesa-vdpau-drivers.i686 \
libva

# Pop in Bazzite patched stuff
declare -A toswap=( \
    ["copr:copr.fedorainfracloud.org:bazzite-org:bazzite"]="wireplumber bootc" \
    ["copr:copr.fedorainfracloud.org:bazzite-org:bazzite-multilib"]="pipewire bluez xorg-x11-server-Xwayland" \
    ["terra-extras"]="switcheroo-control" \
    ["terra-mesa"]="mesa-filesystem" \
    ["copr:copr.fedorainfracloud.org:ublue-os:staging"]="fwupd" \
) && \
for repo in "${!toswap[@]}"; do \
    for package in ${toswap[$repo]}; do dnf5 -y swap --repo=$repo $package $package; done; \
done && unset -v toswap repo package

# Mullvad
dnf5 -y config-manager addrepo --from-repofile=https://repository.mullvad.net/rpm/stable/mullvad.repo
dnf5 -y install mullvad-vpn
