#!/usr/bin/bash

set -eoux pipefail

# Modularizing the Copr instructions here too to make my life easier
dnf5 -y copr enable ublue-os/packages
dnf5 -y copr enable ublue-os/staging
dnf5 -y copr enable bazzite-org/bazzite
dnf5 -y copr enable bazzite-org/bazzite-multilib
dnf5 -y copr enable bieszczaders/kernel-cachyos-addons
dnf5 -y copr enable trixieua/mutter-patched

# Terra
dnf5 -y install --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release{,-extras}